services:
  - postgresql
  - memcached
language: ruby
rvm:
  - 2.7.1
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11 postgresql-server-dev-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - psql --version
  - gem install bundler -v 2.1.4
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE test_db;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
script: bundle exec rake test
